name: auto-release

on:
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  create-release:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
    -
      name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v0.0.${{ github.run_number }}
        name: Release V0.0.${{ github.run_number }}
